"""initial mig

Revision ID: 5fa8c66e1874
Revises: 
Create Date: 2024-07-30 23:01:52.514302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa8c66e1874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spreadsheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spreadsheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spreadsheet_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spreadsheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spreadsheet_name'))

    op.drop_table('spreadsheet')
    # ### end Alembic commands ###
